// <auto-generated />
namespace _4_MySqlDbFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AjoutClasseUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AjoutClasseUser));
        
        string IMigrationMetadata.Id
        {
            get { return "202105191351591_AjoutClasseUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
