// <auto-generated />
namespace _7_CodeFirstDetail.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddClassFournisseur : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddClassFournisseur));
        
        string IMigrationMetadata.Id
        {
            get { return "202105201315001_AddClassFournisseur"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
